sonar.projectKey=TU_USUARIO_TU_REPO
sonar.organization=TU_ORGANIZACION
sonar.projectName=TU_REPO

sonar.sources=.
sonar.exclusions=**/uniagustiniana/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/.pytest_cache/**,**/test_*.py
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml