sonar.projectKey=HernanDavid0711_TallerSonarQube
sonar.organization=TallerSonarQube
sonar.projectName=TallerSonarQube

sonar.sources=.
sonar.exclusions=**/uniagustiniana/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/.pytest_cache/**,**/test_*.py
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml